# Generated by Django 4.1.2 on 2023-03-18 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_hash", models.TextField(default="none")),
                ("name", models.TextField(default="none")),
                ("wallet", models.TextField(default="none")),
                ("age", models.TextField(default="none")),
                ("status", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
