# Generated by Django 4.1.2 on 2023-03-24 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.TextField(default="none")),
                ("name", models.TextField(default="none")),
                ("address", models.TextField(default="none")),
                ("first_address", models.TextField(default="none")),
                ("description", models.TextField(default="none")),
                ("image", models.TextField(default="none")),
                ("status", models.BooleanField(default=True)),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
