# Generated by Django 4.1.2 on 2023-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="age",
            field=models.TextField(default="none"),
        ),
    ]
